services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "9000:9000" # PHP-FPM
    env_file:
      - .env

  node:
    image: node:18-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173" # Vite
    depends_on:
      - app
    command: ["sh", "-c", "tail -f /dev/null"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80" # Serveur Nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306" # Accès à MySQL localement
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_longchamps
      MYSQL_USER: mehdi
      MYSQL_PASSWORD: mehdi
    volumes:
      - dbdata:/var/lib/mysql # Volume pour persister les données

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80" # Accès à PhpMyAdmin via localhost:8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025" # Interface Web Mailpit

volumes:
  dbdata: