services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel_app_production
    restart: always
    volumes:
      - .:/var/www/html:ro # Monté en lecture seule pour éviter les conflits
      - ./storage:/var/www/html/storage # Permet l'écriture sur storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache # Permet l'écriture sur cache
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: nginx_production
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db_production
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: